# Generated by Django 2.1.1 on 2018-09-24 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='QuestionAnswer',
        ),
    ]
